name: zapx.go CD

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

concurrency:
  group: zapx-go-cd
  cancel-in-progress: true

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Get TAG
        id: tag
        run: |
          TAG=${{ github.ref_name }}
          echo TAG=$TAG
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
